### ISSUE TITLE
Trac: Allow non-oxmeta annotations for variables

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#199] opened 2020-05-05 16:14 UTC
https://chaste.cs.ox.ac.uk/trac/ticket/1903

> Child of https://chaste.cs.ox.ac.uk/trac/ticket/1873. Additional related tasks in https://chaste.cs.ox.ac.uk/trac/ticket/2529.

**Comment by MichaelClerx** [comment] 2020-05-05 16:39
See https://github.com/ModellingWebLab/weblab-fc/issues/141

**Comment by jonc125** [comment] 2020-05-06 07:52
The remaining tasks here are just a duplicate of #169.

**Closed by jonc125** 2020-05-06 07:52 UTC
